const WHATS='5599999999999',USD_BRL=5.22,USD_PYG=6120;
const products=[['Carregador Apple USB-C 20W','Carregadores','Apple',140000,'195949121296'],['Auricular Redmi Buds 6 Play','Fones','Xiaomi',91000,'M2420E1'],['Auricular JBL Tune 520BT','Fones','JBL',217000,'JBL520BT'],['Cabo Luxor USB-C para Lightning 27W','Cabos','Luxor',70000,'LX9736B'],['iPhone 15 128GB','Celulares','Apple',5350000,'IP15128'],['Samsung Galaxy A55 256GB','Celulares','Samsung',2550000,'A55256'],['Controle DualSense PS5','Games','Sony',520000,'DSPS5'],['Notebook Lenovo IdeaPad i5','Informática','Lenovo',4250000,'LENI5'],['Apple Watch Series 9','Relógios','Apple',2350000,'AWS9'],['Echo Dot 5ª Geração','Casa Inteligente','Amazon',365000,'ECHODOT5'],['AirPods Pro 3','Fones','Apple',1572000,'AIRPRO3'],['Cabo USB-C 100W','Cabos','Baseus',42000,'USB100W']].map((p,i)=>({id:i+1,name:p[0],category:p[1],brand:p[2],price:p[3],code:p[4],description:`${p[0]} é uma opção prática para quem procura qualidade, tecnologia e bom custo-benefício na X Connect Importados PY.`,spec:['Produto original/importado','Garantia da loja','Pedido direto via WhatsApp']}));
const st={cat:'Todos',search:'',brand:'all',sort:'relevance',sel:null,qty:1};
const $=s=>document.querySelector(s),fmt=v=>`Gs. ${v.toLocaleString('pt-BR')}`;
function svg(p){const icons={Carregadores:'🔌',Fones:'🎧',Cabos:'🔗',Celulares:'📱',Games:'🎮',Informática:'💻',Relógios:'⌚','Casa Inteligente':'🔊'};return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="380" height="320"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#f8fafc"/><stop offset="1" stop-color="#eaf3ff"/></linearGradient></defs><rect width="380" height="320" rx="28" fill="url(#g)"/><circle cx="190" cy="140" r="86" fill="#fff" stroke="#dbe5f0" stroke-width="6"/><text x="190" y="170" text-anchor="middle" font-size="92">${icons[p.category]||'📦'}</text><text x="190" y="292" text-anchor="middle" font-family="Arial" font-size="18" font-weight="800" fill="#64748b">${p.brand}</text></svg>`)}`}
function whats(p,q=1){return `https://wa.me/${WHATS}?text=${encodeURIComponent(`Olá! Tenho interesse no produto: ${p.name} (${p.code}). Quantidade: ${q}. Valor: ${fmt(p.price)}.`)}`}
function cats(){return ['Todos',...new Set(products.map(p=>p.category))]}
function brands(){return [...new Set(products.map(p=>p.brand))].sort()}
function renderCats(){$('#categoryChips').innerHTML=cats().map(c=>`<button class="filters__chip ${st.cat===c?'is-active':''}" data-cat="${c}" type="button">${c}</button>`).join('')}
function renderBrands(){$('#brandSelect').innerHTML='<option value="all">Todas as marcas</option>'+brands().map(b=>`<option>${b}</option>`).join('')}
function filtered(){let r=products.filter(p=>(st.cat==='Todos'||p.category===st.cat)&&(st.brand==='all'||p.brand===st.brand)&&(!st.search||[p.name,p.brand,p.category,p.code].join(' ').toLowerCase().includes(st.search.toLowerCase())));if(st.sort==='priceAsc')r.sort((a,b)=>a.price-b.price);if(st.sort==='priceDesc')r.sort((a,b)=>b.price-a.price);if(st.sort==='nameAsc')r.sort((a,b)=>a.name.localeCompare(b.name));return r}
function render(){const r=filtered();$('#productCount').textContent=`Mostrando produtos 1 - ${r.length} de ${products.length} no total`;$('#productGrid').innerHTML=r.map(p=>`<article class="product-card"><div class="product-card__image-wrap"><img class="product-card__image" src="${svg(p)}" alt="${p.name}"></div><p class="product-card__category">${p.category}</p><h3 class="product-card__title">${p.name}</h3><p class="product-card__brand">${p.brand}</p><p class="product-card__price">${fmt(p.price)}</p><div class="product-card__actions"><button class="product-card__button" data-detail="${p.id}">Ver detalhes</button><button class="product-card__button product-card__button--outline" data-wa="${p.id}">Consultar</button></div></article>`).join('')||'<p>Nenhum produto encontrado.</p>'}
function openProd(id){const p=products.find(x=>x.id==id);st.sel=p;st.qty=1;const im=svg(p);$('#detailImage').src=im;$('#detailImage').alt=p.name;$('#detailThumb').src=im;$('#detailThumb').alt=p.name;$('#detailCategory').textContent=p.category;$('#detailTitle').textContent=p.name;$('#detailPrice').textContent=fmt(p.price);$('#detailBrand').textContent=p.brand;$('#detailCode').textContent=p.code;$('#detailDescription').textContent=p.description;$('#detailSpecs').innerHTML=p.spec.map(s=>`<li>${s}</li>`).join('');$('#qtyValue').textContent=1;$('#detailWhatsapp').href=whats(p,1);$('#catalogo').hidden=true;$('#categorias').hidden=true;$('#produto').hidden=false;$('#produto').scrollIntoView({behavior:'smooth'})}
function closeProd(){$('#produto').hidden=true;$('#catalogo').hidden=false;$('#categorias').hidden=false;$('#catalogo').scrollIntoView({behavior:'smooth'})}
function qty(d){if(!st.sel)return;st.qty=Math.max(1,st.qty+d);$('#qtyValue').textContent=st.qty;$('#detailWhatsapp').href=whats(st.sel,st.qty)}
function convert(){const usd=Number($('#usdValue').value||0),cur=$('#currencySelect').value,val=usd*(cur==='PYG'?USD_PYG:USD_BRL);$('#conversionLabel').textContent=cur==='PYG'?'Total em Guarani':'Total em Real';$('#conversionResult').textContent=cur==='PYG'?`Gs ${Math.round(val).toLocaleString('pt-BR')}`:val.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
document.addEventListener('click',e=>{const c=e.target.closest('[data-cat]');if(c){st.cat=c.dataset.cat;renderCats();render()}const d=e.target.closest('[data-detail]');if(d)openProd(d.dataset.detail);const w=e.target.closest('[data-wa]');if(w){const p=products.find(x=>x.id==w.dataset.wa);window.open(whats(p),'_blank','noopener')}});
$('#searchInput').addEventListener('input',e=>{st.search=e.target.value;render()});$('.navbar__search').addEventListener('submit',e=>{e.preventDefault();$('#catalogo').scrollIntoView({behavior:'smooth'})});$('#brandSelect').addEventListener('change',e=>{st.brand=e.target.value;render()});$('#sortSelect').addEventListener('change',e=>{st.sort=e.target.value;render()});$('#usdValue').addEventListener('input',convert);$('#currencySelect').addEventListener('change',convert);$('#backToCatalog').addEventListener('click',closeProd);$('#qtyMinus').addEventListener('click',()=>qty(-1));$('#qtyPlus').addEventListener('click',()=>qty(1));$('#copyProduct').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(`${st.sel.name} - ${fmt(st.sel.price)}`);$('#copyProduct').textContent='Copiado';setTimeout(()=>$('#copyProduct').textContent='Copiar link',1300)}catch{}});$('.navbar__toggle').addEventListener('click',()=>{const b=$('.navbar__toggle'),m=$('#navbarMenu'),o=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',!o);m.classList.toggle('is-open')});
const url=`https://wa.me/${WHATS}?text=${encodeURIComponent('Olá! Gostaria de ver o catálogo da X Connect.')}`;['#navWhatsapp','#heroWhatsapp','#floatingWhatsapp'].forEach(s=>$(s).href=url);renderCats();renderBrands();render();convert();
